# Generated by Django 5.2.6 on 2026-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLA_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mla_name', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('terms_served', models.IntegerField()),
                ('development_projects', models.IntegerField()),
                ('party_affiliation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mp_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('terms_served', models.IntegerField()),
                ('bills_passed', models.IntegerField()),
                ('party_affiliation', models.CharField(max_length=100)),
            ],
        ),
    ]
