# Generated by Django 5.2.6 on 2026-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor_Actress_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('movies_done', models.IntegerField()),
                ('awards_won', models.IntegerField()),
                ('debut_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('movies_directed', models.IntegerField()),
                ('awards_won', models.IntegerField()),
                ('debut_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Writer_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('articles_written', models.IntegerField()),
                ('awards_won', models.IntegerField()),
            ],
        ),
    ]
