# Generated by Django 5.2.6 on 2026-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('runs_scored', models.IntegerField()),
                ('wickets_taken', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supporting_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_name', models.CharField(max_length=100)),
                ('S_Position', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience_years', models.IntegerField()),
            ],
        ),
    ]
