# Generated by Django 5.2.6 on 2025-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regd', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
