# Generated by Django 5.2.6 on 2026-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
