# Generated by Django 5.2.6 on 2026-01-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shirt',
            new_name='Electronics',
        ),
    ]
